name: dockerci

on: 
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag
      - name: Extract tag name without v
        shell: bash
        run: echo "##[set-output name=tagv;]$(echo ${GITHUB_REF#refs/tags/v})"
        id: extract_tag_v
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: novela_api
          platforms: linux/amd64
          push: true
          tags: |
            razikus/novela:api-${{ steps.extract_tag.outputs.tag }}
            razikus/novela:api-${{ steps.extract_tag_v.outputs.tagv }}
      -
        name: Build and push gui
        uses: docker/build-push-action@v2
        with:
          context: novela-gui
          platforms: linux/amd64
          push: true
          tags: |
            razikus/novela:gui-${{ steps.extract_tag.outputs.tag }}
            razikus/novela:gui-${{ steps.extract_tag_v.outputs.tagv }}
